### ISSUE TITLE
Inability to recognize dots

### ISSUE THREAD

**Issue by drepram** [sonnylazuardi/cek-ejaan#1]
![image](https://user-images.githubusercontent.com/34530026/147638658-09b8f497-b51e-4dad-a34b-c350ad475dd4.png)

As can be seen in the image above, `dst.` is present but the app does not seem to be recognizing it and kept on recommending `dst.` which would as a consequence result in `dst....` as the iteration goes many-many times.

**Comment by sonnylazuardi** [comment]
Fixed in the next release

![image](https://user-images.githubusercontent.com/856609/147645822-d816910d-b0f3-4924-ba22-bab3395f0130.png)
